export default {
    logo : require('../asset/logo.png'),
    bottomButton : require('../asset/bottomButton.png'),
    graphCircle: require('../asset/circle.png'),
    graphCircled: require('../asset/circleAccount.png'),
    dotIcon: require('../asset/dotIcon.png'),
    add: require('../asset/add.png'),
    bot: require('../asset/bot.png'),
    user: require('../asset/user.png'),
    wait: require('../asset/wait.gif'),
    star: require('../asset/star.png'),
    close: require('../asset/close.png'),
    bigStar: require('../asset/bigStar.png'),
    cross: require('../asset/cross.png'),
    transfer: require('../asset/button-transfer.png'),
    userTransfert: require('../asset/user-transfert.png'),
    success: require('../asset/success.png'),
    setting: require('../asset/setting.png'),
    jackpot: require('../asset/jackpot.png'),
    batiment: require('../asset/design_batiment.png'),
    bim: require('../asset/design_bim.png'),
    qrcode : require('../asset/QRCode.png'),
    burger: require('../asset/design_burger.png'),
    pasteque: require('../asset/design_pasteque.png'),
    virementSpeed: require('../asset/virement_speed.gif'),
    transfertConfirm1: require('../asset/transfertConfirm1.png'),
    transfertConfirm2: require('../asset/transfertConfirm2.png'),
    carte1: require('../asset/Carte1.png'),
    carte2: require('../asset/Carte2.png'),
    carte3: require('../asset/Carte3.png'),
    carte4: require('../asset/Carte4.png'),
    back: require('../asset/back.png'),
    back_green: require('../asset/back_green.png'),
    back_dark: require('../asset/back_dark.png'),
    next: require('../asset/next.png'),
    pin: require('../asset/pin.png'),
    check: require('../asset/Check_small_contact.png'),
    cagnotteConfirm: require('../asset/cagnotteConfirm.png'),
    pointsSpeed: require('../asset/point_speed.gif'),
    pointsImage: require('../asset/pointsImage.png'),
    burgerPicto: require('../asset/burger.png'),
    bimPicto: require('../asset/bim_logo.png'),
    batimentPicto: require('../asset/boutique.png'),
    keyboard:{
        1:  require('../asset/keyboard/1.png'),
        2:  require('../asset/keyboard/2.png'),
        3:  require('../asset/keyboard/3.png'),
        4:  require('../asset/keyboard/4.png'),
        5:  require('../asset/keyboard/5.png'),
        6:  require('../asset/keyboard/6.png'),
        7:  require('../asset/keyboard/7.png'),
        8:  require('../asset/keyboard/8.png'),
        9:  require('../asset/keyboard/9.png'),
        0:  require('../asset/keyboard/0.png'),
        'effacer':  require('../asset/keyboard/effacer.png'),
        'virgule':  require('../asset/keyboard/virgule.png')
    },
    users:{
		1:  require('../asset/users/1.png'),
		2:  require('../asset/users/2.png'),
		3:  require('../asset/users/3.png'),
		4:  require('../asset/users/4.png')
	},
    tabs: {
        white: require('../asset/tabs/white.png'),
        yellow: require('../asset/tabs/yellow.png'),
        violet: require('../asset/tabs/violet.png'),
        blue: require('../asset/tabs/blue.png'),
        orange: require('../asset/tabs/orange.png'),
        cyan: require('../asset/tabs/cyan.png'),
        green: require('../asset/tabs/green.png'),
        lemon: require('../asset/tabs/lemon.png'),
        lightblue: require('../asset/tabs/lightblue.png'),
        lightviolet: require('../asset/tabs/lightviolet.png'),
        mauve: require('../asset/tabs/mauve.png'),
        red: require('../asset/tabs/red.png')
    },
    screens: {
        contactsList: require('../asset/screens/contactsList.png'),
        contact: require('../asset/screens/contact.png'),
        journal: require('../view/journal/asset/screen.png'),
        login: require('../asset/screens/login.png')
    }
};
