export default {
    logo : require('./logo.png'),
    bottomButton : require('./bottomButton.png'),
    graphCircle: require('./circle.png'),
    graphCircled: require('./circleAccount.png'),
    dotIcon: require('./dotIcon.png'),
    add: require('./add.png'),
    bot: require('./bot.png'),
    user: require('./user.png'),
    wait: require('./wait.gif'),
    close: require('./close.png'),
    transfer: require('./button-transfer.png'),
    c3po: require('./c3po.png'),
    userTransfert: require('./user-transfert.png'),
    success: require('./success.png'),
    setting: require('./setting.png'),
    jackpot: require('./jackpot.png'),
    batiment: require('./design_batiment.png'),
    bim: require('./design_bim.png'),
    burger: require('./design_burger.png'),
    pasteque: require('./design_pasteque.png'),
    virementSpeed: require('./virement_speed.gif'),
    transfertConfirm1: require('./transfertConfirm1.png'),
    transfertConfirm2: require('./transfertConfirm2.png'),
    carte1: require('./Carte1.png'),
    carte2: require('./Carte2.png'),
    carte3: require('./Carte3.png'),
    carte4: require('./Carte4.png'),
    keyboard:{
        1:  require('./keyboard/1.png'),
        2:  require('./keyboard/2.png'),
        3:  require('./keyboard/3.png'),
        4:  require('./keyboard/4.png'),
        5:  require('./keyboard/5.png'),
        6:  require('./keyboard/6.png'),
        7:  require('./keyboard/7.png'),
        8:  require('./keyboard/8.png'),
        9:  require('./keyboard/9.png'),
        0:  require('./keyboard/0.png'),
        'effacer':  require('./keyboard/effacer.png'),
        'virgule':  require('./keyboard/virgule.png')
    },
    users:{
		1:  require('./users/1.png'),
		2:  require('./users/2.png'),
		3:  require('./users/3.png'),
		4:  require('./users/4.png')
	},
    tabs: {
        white: require('./tabs/white.png'),
        yellow: require('./tabs/yellow.png'),
        violet: require('./tabs/violet.png'),
        blue: require('./tabs/blue.png'),
        orange: require('./tabs/orange.png'),
        cyan: require('./tabs/cyan.png'),
        green: require('./tabs/green.png'),
        lemon: require('./tabs/lemon.png'),
        lightblue: require('./tabs/lightblue.png'),
        lightviolet: require('./tabs/lightviolet.png'),
        mauve: require('./tabs/mauve.png'),
        red: require('./tabs/red.png')
    },
    screens: {
        parameters: require('./screens/parameters.png'),
        contactsList: require('./screens/contactsList.png'),
        contact: require('./screens/contact.png'),
        profile: require('./screens/profile.png'),
        journal: require('./screens/journal.png'),
        login: require('./screens/login.png')
    }
};
